language: erlang
otp_release:
  - 20.1
  - 19.3
  - 18.3
  - 17.5

env:
  - PATH=$HOME/.cache/rebar3/bin/:$PATH

before_script:
  - curl -O -L https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - ./rebar3 update

script: "rm -rf deps ebin test/*.beam logs && ./rebar3 compile"

branches:
  only:
    - master
